# Generated by Django 5.2 on 2025-06-30 20:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="image"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="псевдоним"
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="артикул"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="старая цена",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="короткое описание"),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="полное описание"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="остаток"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно"),
                ),
                (
                    "germination_time",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="время проростания"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "легкая"),
                            ("medium", "средняя"),
                            ("hard", "сложная"),
                        ],
                        max_length=10,
                        verbose_name="сложность выращивания",
                    ),
                ),
                (
                    "taste_characteristics",
                    models.TextField(
                        blank=True, verbose_name="вкусовые характеристики"
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, verbose_name="полезные свойства"),
                ),
                (
                    "recommended_substrate",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="рекомендуемый субстрат",
                    ),
                ),
                (
                    "growing_instructions",
                    models.TextField(
                        blank=True, verbose_name="инструкция по проращиванию"
                    ),
                ),
                (
                    "recommended_temperature",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="рекомендуемая температура",
                    ),
                ),
                (
                    "harvest_dates",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="дата сбора"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="изображение"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="основное"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="заказ")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение продукта",
                "verbose_name_plural": "изображения продукта",
                "ordering": ["order"],
            },
        ),
    ]
