# Generated by Django 5.2 on 2025-06-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order"],
                "verbose_name": "изображение продукта",
                "verbose_name_plural": "изображения продукта",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Легкая"),
                    ("medium", "Средняя"),
                    ("hard", "Сложная"),
                ],
                max_length=10,
                verbose_name="difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="full_description",
            field=models.TextField(blank=True, verbose_name="полное описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="growing_instructions",
            field=models.TextField(
                blank=True, verbose_name="инструкция по проращиванию"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="harvest_dates",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="дата сбора"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активно"),
        ),
        migrations.AlterField(
            model_name="product",
            name="recommended_substrate",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="рекомендуемый субстрат"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="recommended_temperature",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="рекомендуемая температура"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="короткое описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="остаток"),
        ),
        migrations.AlterField(
            model_name="product",
            name="taste_characteristics",
            field=models.TextField(blank=True, verbose_name="вкусовые характеристики"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="изображение"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="основное"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="заказ"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="продукт",
            ),
        ),
    ]
