# Generated by Django 5.2 on 2025-06-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(max_length=50, unique=True, verbose_name="статья"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "легкая"),
                    ("medium", "средняя"),
                    ("hard", "сложная"),
                ],
                max_length=10,
                verbose_name="difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="цена"
            ),
        ),
    ]
