# Generated by Django 5.2 on 2025-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_article_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="benefits",
            field=models.TextField(blank=True, verbose_name="полезные свойства"),
        ),
        migrations.AlterField(
            model_name="product",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "легкая"),
                    ("medium", "средняя"),
                    ("hard", "сложная"),
                ],
                max_length=10,
                verbose_name="сложность выращивания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="germination_time",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="время проростания"
            ),
        ),
    ]
