# Generated by Django 5.2 on 2025-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_old_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(max_length=50, unique=True, verbose_name="артикул"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="псевдоним"
            ),
        ),
    ]
