# Generated by Django 5.2 on 2025-06-30 20:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discounts", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В работе"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Кредитная карта"), ("cash", "Наличными")],
                        default="card",
                        max_length=20,
                        verbose_name="метод оплаты",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("post", "Почта России"),
                            ("cdek", "СДЭК"),
                            ("pickup", "Самовывоз"),
                        ],
                        default="post",
                        max_length=20,
                        verbose_name="способ доставки",
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="стоимость доставки",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="итого"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="адрес электронной почты"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="номер телефона"),
                ),
                ("address", models.TextField(blank=True, verbose_name="адрес")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="индекс"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="город"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="страна"),
                ),
                (
                    "cdek_point_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="СДЭК ПВЗ ID point ID"
                    ),
                ),
                (
                    "cdek_point_address",
                    models.TextField(blank=True, verbose_name="СДЭК ПВЗ адрес"),
                ),
                (
                    "need_consultation",
                    models.BooleanField(
                        default=False, verbose_name="нужна консультация"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="примечание к заказу"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="размер скидки",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID оплаты в Yookassa"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание оплаты"),
                            ("waiting_for_capture", "Ожидание подтверждения оплаты"),
                            ("succeeded", "Оплачен"),
                            ("canceled", "Отменен"),
                            ("refunded", "Возрат денег"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ответ Yookassa"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Временная метка оплаты"
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discounts.promocode",
                        verbose_name="промо код",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="количество"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция",
                "verbose_name_plural": "позиции",
            },
        ),
    ]
