# Generated by Django 5.2 on 2025-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_discount_amount_order_promo_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
