# Generated by Django 5.2 on 2025-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Временная метка оплаты"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Ответ Yookassa"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Yookassa Payment ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="стоимость доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("post", "Почта России"),
                    ("cdek", "СДЭК"),
                    ("pickup", "Самовывоз"),
                ],
                default="post",
                max_length=20,
                verbose_name="способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="фамилия"),
        ),
        migrations.AlterField(
            model_name="order",
            name="need_consultation",
            field=models.BooleanField(default=False, verbose_name="нужна консультация"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Кредитная карта"), ("cash", "Наличными")],
                default="card",
                max_length=20,
                verbose_name="метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("waiting_for_capture", "Waiting for Capture"),
                    ("succeeded", "Paid"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="номер телефона"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В процессе"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="new",
                max_length=20,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="итого"
            ),
        ),
    ]
