# Generated by Django 5.2 on 2025-06-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_paid_at_order_payment_data_order_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ip_address",
        ),
    ]
