# Generated by Django 5.2 on 2025-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание оплаты"),
                    ("waiting_for_capture", "Ожидание подтверждения оплаты"),
                    ("succeeded", "Оплачен"),
                    ("canceled", "Отменен"),
                    ("refunded", "Возрат денег"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
