# Generated by Django 5.2 on 2025-06-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "состав заказа",
                "verbose_name_plural": "состав заказа",
            },
        ),
    ]
