# Generated by Django 5.2 on 2025-06-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_orderitem_order_alter_orderitem_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "позиция", "verbose_name_plural": "позиции"},
        ),
    ]
