# Generated by Django 5.2 on 2025-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="cdek_point_address",
            field=models.TextField(blank=True, verbose_name="СДЭК ПВЗ адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="cdek_point_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="СДЭК ПВЗ ID point ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="город"),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="страна"),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="индекс"),
        ),
    ]
