# Generated by Django 5.2 on 2025-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_address_alter_order_cdek_point_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="примечание к заказу"),
        ),
    ]
