# Generated by Django 5.2 on 2025-06-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0010_alter_promocode_max_discount"),
        ("orders", "0013_alter_order_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="размер скидки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID оплаты в Yookassa"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discounts.promocode",
                verbose_name="промо код",
            ),
        ),
    ]
