# Generated by Django 5.2 on 2025-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Покупатель"),
                    ("staff", "Персонал"),
                    ("admin", "Админ"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
