# Generated by Django 5.2 on 2025-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="О себе"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, verbose_name="Отдел"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Идентификатор"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Покупатель"),
                    ("staff", "Персонал"),
                    ("admin", "Админ"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
