# Generated by Django 5.2 on 2025-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_avatar_alter_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="Адрес"),
        ),
    ]
