services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
    # networks:
    #   - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: microgreens
      POSTGRES_USER: dbadmin
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homework_user -d homework_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine

  # celery:
  #   build: .
  #   command: celery -A config worker -l info
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:

networks:
  app-network:
