SELECT 'CREATE DATABASE microgreens'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'microgreens')\gexec

GRANT ALL PRIVILEGES ON DATABASE microgreens TO dbadmin;

\c microgreens

GRANT ALL ON SCHEMA public TO dbadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dbadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dbadmin;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dbadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dbadmin;
