# Generated by Django 5.2 on 2025-06-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("discounts", "0003_alter_promocodeuse_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discounts.promocode",
                verbose_name="promo code",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="promo_code_applied",
            field=models.BooleanField(default=False, verbose_name="promo code applied"),
        ),
    ]
