from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class Report(TimeStampedModel):
    """Base report model"""

    class ReportType(models.TextChoices):
        SALES = "sales", _("Sales")
        PRODUCTS = "products", _("Products")
        INVENTORY = "inventory", _("Inventory")
        CUSTOMERS = "customers", _("Customers")

    name = models.CharField(_("name"), max_length=100)
    report_type = models.CharField(
        _("report type"), max_length=20, choices=ReportType.choices
    )
    start_date = models.DateField(_("start date"))
    end_date = models.DateField(_("end date"))
    generated_by = models.ForeignKey(
        "users.User",
        verbose_name=_("generated by"),
        on_delete=models.SET_NULL,
        null=True,
    )
    file = models.FileField(_("file"), upload_to="reports/", blank=True, null=True)
    is_ready = models.BooleanField(_("is ready"), default=False)

    class Meta:
        verbose_name = _("report")
        verbose_name_plural = _("reports")
        ordering = ["-created"]

    def __str__(self):
        return self.name
