# Generated by Django 5.2 on 2025-06-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
    ]
