# Generated by Django 5.2 on 2025-06-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_articlecategory_article_view_count_article_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="articlecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
