# Generated by Django 5.2 on 2025-06-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_options_alter_articlecategory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
