# Generated by Django 5.2 on 2025-06-18 12:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="blog.articlecategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время публикации"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Псведоним"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Загаловок"),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="Псведоним"
            ),
        ),
    ]
