# Generated by Django 5.2 on 2025-06-30 20:25

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percent",
                        max_length=10,
                        verbose_name="тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="размер скидки",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальная скидка для процентных скидок",
                        max_digits=10,
                        verbose_name="размер максимальной скидки",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Минимальная сумма заказа для применения скидки",
                        max_digits=10,
                        verbose_name="минимальная сумма заказа",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действует с")),
                ("valid_to", models.DateTimeField(verbose_name="Действует до")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        default=200,
                        help_text="Максимально количество раз, когда можно использовать этот код",
                        verbose_name="максимальное использование uses",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество использований"
                    ),
                ),
                (
                    "for_all_users",
                    models.BooleanField(
                        default=True, verbose_name="доступен для всех пользователей"
                    ),
                ),
                (
                    "for_first_order",
                    models.BooleanField(
                        default=False, verbose_name="только для первого заказа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо код",
                "verbose_name_plural": "Промо коды",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="discount amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Использование промо кода",
                "verbose_name_plural": "Использование промо кодов",
                "ordering": ["-created"],
            },
        ),
    ]
