# Generated by Django 5.2 on 2025-06-12 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=10,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discount value",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount for percentage discounts",
                        max_digits=10,
                        verbose_name="maximum discount",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order amount to apply discount",
                        max_digits=10,
                        verbose_name="minimum order amount",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="valid from")),
                ("valid_to", models.DateTimeField(verbose_name="valid to")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this code can be used",
                        verbose_name="maximum uses",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(default=0, verbose_name="current uses"),
                ),
                (
                    "for_all_users",
                    models.BooleanField(default=True, verbose_name="for all users"),
                ),
                (
                    "for_first_order",
                    models.BooleanField(
                        default=False, verbose_name="for first order only"
                    ),
                ),
            ],
            options={
                "verbose_name": "promo code",
                "verbose_name_plural": "promo codes",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="discount amount"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_code_uses",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uses",
                        to="discounts.promocode",
                        verbose_name="promo code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_code_uses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "promo code use",
                "verbose_name_plural": "promo code uses",
                "ordering": ["-created"],
            },
        ),
    ]
