# Generated by Django 5.2 on 2025-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ["-created"],
                "verbose_name": "Промо код",
                "verbose_name_plural": "Промо коды",
            },
        ),
    ]
