# Generated by Django 5.2 on 2025-06-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discounts", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promocodeuse",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_code_uses",
                to="orders.order",
                verbose_name="order",
            ),
        ),
        migrations.AddField(
            model_name="promocodeuse",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uses",
                to="discounts.promocode",
                verbose_name="promo code",
            ),
        ),
        migrations.AddField(
            model_name="promocodeuse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_code_uses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
