# Generated by Django 5.2 on 2025-06-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0002_alter_promocode_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocodeuse",
            options={
                "ordering": ["-created"],
                "verbose_name": "Использование промо кода",
                "verbose_name_plural": "Использование промо кодов",
            },
        ),
    ]
