# Generated by Django 5.2 on 2025-06-18 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0004_remove_promocodeuse_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promocodeuse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_code_uses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
