# Generated by Django 5.2 on 2025-06-18 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0005_promocodeuse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Процент"), ("fixed", "Фиксированная сумма")],
                default="percent",
                max_length=10,
                verbose_name="тип скидки",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="значение",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Максимальная скидка для процентных скидок",
                max_digits=10,
                verbose_name="максимальная скидка",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True,
                default=200,
                help_text="Максимально количество раз, когда можно использовать этот код",
                verbose_name="максимальное использование uses",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Минимальная сумма заказа для применения скидки",
                max_digits=10,
                verbose_name="минимальная сумма заказа",
            ),
        ),
    ]
