# Generated by Django 5.2 on 2025-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0006_alter_promocode_discount_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_from",
            field=models.DateTimeField(verbose_name="Действует с"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_to",
            field=models.DateTimeField(verbose_name="Действует по"),
        ),
    ]
