# Generated by Django 5.2 on 2025-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0007_alter_promocode_code_alter_promocode_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="valid_to",
            field=models.DateTimeField(verbose_name="Действует до"),
        ),
    ]
