# Generated by Django 5.2 on 2025-06-18 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0008_alter_promocode_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="размер скидки",
            ),
        ),
    ]
