# Generated by Django 5.2 on 2025-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0009_alter_promocode_discount_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Максимальная скидка для процентных скидок",
                max_digits=10,
                verbose_name="размер максимальной скидки",
            ),
        ),
    ]
