# Generated by Django 5.2 on 2025-06-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_page_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["title"],
                "verbose_name": "Веб-страница",
                "verbose_name_plural": "Веб-страницы",
            },
        ),
    ]
