# Generated by Django 5.2 on 2025-06-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created"],
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
    ]
