# Generated by Django 5.2 on 2025-06-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_report_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="generated_by",
        ),
    ]
